export const provincias_peru = [
  { id: 1, nombre_provincia: "Abancay" },
  { id: 2, nombre_provincia: "Acobamba" },
  { id: 3, nombre_provincia: "Aija" },
  { id: 4, nombre_provincia: "Alto Amazonas" },
  { id: 5, nombre_provincia: "Ambo" },
  { id: 6, nombre_provincia: "Andahuaylas" },
  { id: 7, nombre_provincia: "Antabamba" },
  { id: 8, nombre_provincia: "Anta" },
  { id: 9, nombre_provincia: "Arequipa" },
  { id: 10, nombre_provincia: "Ascope" },
  { id: 11, nombre_provincia: "Aymaraes" },
  { id: 12, nombre_provincia: "Barranca" },
  { id: 13, nombre_provincia: "Bellavista" },
  { id: 14, nombre_provincia: "Bolognesi" },
  { id: 15, nombre_provincia: "Bongará" },
  { id: 16, nombre_provincia: "Cajabamba" },
  { id: 17, nombre_provincia: "Cajamarca" },
  { id: 18, nombre_provincia: "Cajatambo" },
  { id: 19, nombre_provincia: "Camaná" },
  { id: 20, nombre_provincia: "Canas" },
  { id: 21, nombre_provincia: "Carabaya" },
  { id: 22, nombre_provincia: "Caravelí" },
  { id: 23, nombre_provincia: "Casma" },
  { id: 24, nombre_provincia: "Castilla" },
  { id: 25, nombre_provincia: "Caylloma" },
  { id: 26, nombre_provincia: "Celendín" },
  { id: 27, nombre_provincia: "Cerro de Pasco" },
  { id: 28, nombre_provincia: "Chachapoyas" },
  { id: 29, nombre_provincia: "Chanchamayo" },
  { id: 30, nombre_provincia: "Chepén" },
  { id: 31, nombre_provincia: "Chiclayo" },
  { id: 32, nombre_provincia: "Chincha" },
  { id: 33, nombre_provincia: "Chota" },
  { id: 34, nombre_provincia: "Chumbivilcas" },
  { id: 35, nombre_provincia: "Concepción" },
  { id: 36, nombre_provincia: "Condesuyos" },
  { id: 37, nombre_provincia: "Contumazá" },
  { id: 38, nombre_provincia: "Cotabambas" },
  { id: 39, nombre_provincia: "Cusco" },
  { id: 40, nombre_provincia: "Cutervo" },
  { id: 41, nombre_provincia: "Daniel Alcides Carrión" },
  { id: 42, nombre_provincia: "Datem del Marañón" },
  { id: 43, nombre_provincia: "Dos de Mayo" },
  { id: 44, nombre_provincia: "Espinar" },
  { id: 45, nombre_provincia: "Ferreñafe" },
  { id: 46, nombre_provincia: "General Sánchez Cerro" },
  { id: 47, nombre_provincia: "Germán Busch" },
  { id: 48, nombre_provincia: "Gran Chimú" },
  { id: 49, nombre_provincia: "Grau" },
  { id: 50, nombre_provincia: "Huacaybamba" },
  { id: 51, nombre_provincia: "Huacavelica" },
  { id: 52, nombre_provincia: "Huallaga" },
  { id: 53, nombre_provincia: "Huamalíes" },
  { id: 54, nombre_provincia: "Huamanga" },
  { id: 55, nombre_provincia: "Huancabamba" },
  { id: 56, nombre_provincia: "Huancané" },
  { id: 57, nombre_provincia: "Huancavelica" },
  { id: 58, nombre_provincia: "Huánuco" },
  { id: 59, nombre_provincia: "Huanta" },
  { id: 60, nombre_provincia: "Huarmey" },
  { id: 61, nombre_provincia: "Huaylas" },
  { id: 62, nombre_provincia: "Huaytará" },
  { id: 63, nombre_provincia: "Huaral" },
  { id: 64, nombre_provincia: "Huaraz" },
  { id: 65, nombre_provincia: "Huari" },
  { id: 66, nombre_provincia: "Huarmey" },
  { id: 67, nombre_provincia: "Huaylas" },
  { id: 68, nombre_provincia: "Huaytará" },
  { id: 69, nombre_provincia: "Huaral" },
  { id: 70, nombre_provincia: "Huaraz" },
  { id: 71, nombre_provincia: "Huari" },
  { id: 72, nombre_provincia: "Huánuco" },
  { id: 73, nombre_provincia: "Huarochirí" },
  { id: 74, nombre_provincia: "Ica" },
  { id: 75, nombre_provincia: "Ilo" },
  { id: 76, nombre_provincia: "Ilo" },
  { id: 77, nombre_provincia: "Ilave" },
  { id: 78, nombre_provincia: "Ilo" },
  { id: 79, nombre_provincia: "Isabel" },
  { id: 80, nombre_provincia: "Islay" },
  { id: 81, nombre_provincia: "Jauja" },
  { id: 82, nombre_provincia: "Jorge Basadre" },
  { id: 83, nombre_provincia: "Juli" },
  { id: 84, nombre_provincia: "Junín" },
  { id: 85, nombre_provincia: "La Convención" },
  { id: 86, nombre_provincia: "La Joya" },
  { id: 87, nombre_provincia: "La Libertad" },
  { id: 88, nombre_provincia: "Lambayeque" },
  { id: 89, nombre_provincia: "Lampa" },
  { id: 90, nombre_provincia: "Lares" },
  { id: 91, nombre_provincia: "Lima" },
  { id: 92, nombre_provincia: "Linares" },
  { id: 93, nombre_provincia: "Lircay" },
  { id: 94, nombre_provincia: "Loreto" },
  { id: 95, nombre_provincia: "Lucanas" },
  { id: 96, nombre_provincia: "Luya" },
  { id: 97, nombre_provincia: "Majes" },
  { id: 98, nombre_provincia: "Manu" },
  { id: 99, nombre_provincia: "Mariscal Cáceres" },
  { id: 100, nombre_provincia: "Mariscal Luzuriaga" },
  { id: 101, nombre_provincia: "Mariscal Nieto" },
  { id: 102, nombre_provincia: "Mariscal Ramón Castilla" },
  { id: 103, nombre_provincia: "Maynas" },
  { id: 104, nombre_provincia: "Melgar" },
  { id: 105, nombre_provincia: "Moho" },
  { id: 106, nombre_provincia: "Mollebamba" },
  { id: 107, nombre_provincia: "Momón" },
  { id: 108, nombre_provincia: "Morropon" },
  { id: 109, nombre_provincia: "Morropón" },
  { id: 110, nombre_provincia: "Motupe" },
  { id: 111, nombre_provincia: "Nasca" },
  { id: 112, nombre_provincia: "Ocros" },
  { id: 113, nombre_distrito: "Otuzco" },
  { id: 114, nombre_distrito: "Oyón" },
  { id: 115, nombre_distrito: "Paucar del Sara Sara" },
  { id: 116, nombre_distrito: "Pachitea" },
  { id: 117, nombre_distrito: "Pacocha" },
  { id: 118, nombre_distrito: "Pallasca" },
  { id: 119, nombre_distrito: "Pallasca" },
  { id: 120, nombre_distrito: "Palpa" },
  { id: 121, nombre_distrito: "Paucar del Sara Sara" },
  { id: 122, nombre_distrito: "Paita" },
  { id: 123, nombre_distrito: "Palca" },
  { id: 124, nombre_distrito: "Pallares" },
  { id: 125, nombre_distrito: "Pampas" },
  { id: 126, nombre_distrito: "Parinacochas" },
  { id: 127, nombre_distrito: "Paruro" },
  { id: 128, nombre_distrito: "Pasco" },
  { id: 129, nombre_distrito: "Pataz" },
  { id: 130, nombre_distrito: "Patas" },
  { id: 131, nombre_distrito: "Pauza" },
  { id: 132, nombre_distrito: "Pedro Gálvez" },
  { id: 133, nombre_distrito: "Pedro Vilca Apaza" },
  { id: 134, nombre_distrito: "Pisco" },
  { id: 135, nombre_distrito: "Pomabamba" },
  { id: 136, nombre_distrito: "Pomata" },
  { id: 137, nombre_distrito: "Puno" },
  { id: 138, nombre_distrito: "Puquio" },
  { id: 139, nombre_distrito: "Putumayo" },
  { id: 140, nombre_distrito: "Quispicanchi" },
  { id: 141, nombre_distrito: "Requena" },
  { id: 142, nombre_distrito: "Río Tambo" },
  { id: 143, nombre_distrito: "San Ignacio" },
  { id: 144, nombre_distrito: "San Marcos" },
  { id: 145, nombre_distrito: "San Miguel" },
  { id: 146, nombre_distrito: "San Pablo" },
  { id: 147, nombre_distrito: "San Román" },
  { id: 148, nombre_distrito: "Santa" },
  { id: 149, nombre_distrito: "Santa Cruz" },
  { id: 150, nombre_distrito: "Santa María" },
  { id: 151, nombre_distrito: "Santiago de Chuco" },
  { id: 152, nombre_distrito: "Santiago de Chuco" },
  { id: 153, nombre_distrito: "Satipo" },
  { id: 154, nombre_distrito: "Sechura" },
  { id: 155, nombre_distrito: "Sihuas" },
  { id: 156, nombre_distrito: "Sihuas" },
  { id: 157, nombre_distrito: "Sillapata" },
  { id: 158, nombre_distrito: "Sorochuco" },
  { id: 159, nombre_distrito: "Sucre" },
  { id: 160, nombre_distrito: "Tacna" },
  { id: 161, nombre_distrito: "Tahuamanu" },
  { id: 162, nombre_distrito: "Talara" },
  { id: 163, nombre_distrito: "Tamarindo" },
  { id: 164, nombre_distrito: "Tambopata" },
  { id: 165, nombre_distrito: "Tayacaja" },
  { id: 166, nombre_distrito: "Tocache" },
  { id: 167, nombre_distrito: "Toquepala" },
  { id: 168, nombre_distrito: "Trujillo" },
  { id: 169, nombre_distrito: "Túcume" },
  { id: 170, nombre_distrito: "Urubamba" },
  { id: 171, nombre_distrito: "Utcubamba" },
  { id: 172, nombre_distrito: "Víctor Fajardo" },
  { id: 173, nombre_distrito: "Vilcabamba" },
  { id: 174, nombre_distrito: "Vilcas Huamán" },
  { id: 175, nombre_distrito: "Vilcashuamán" },
  { id: 176, nombre_distrito: "Virú" },
  { id: 177, nombre_distrito: "Yauli" },
  { id: 178, nombre_distrito: "Yaután" },
];

export const departamentos_peru = [
  { id: 1, nombre_departamento: "Amazonas" },
  { id: 2, nombre_departamento: "Áncash" },
  { id: 3, nombre_departamento: "Apurímac" },
  { id: 4, nombre_departamento: "Arequipa" },
  { id: 5, nombre_departamento: "Ayacucho" },
  { id: 6, nombre_departamento: "Cajamarca" },
  { id: 7, nombre_departamento: "Callao" },
  { id: 8, nombre_departamento: "Cusco" },
  { id: 9, nombre_departamento: "Huancavelica" },
  { id: 10, nombre_departamento: "Huánuco" },
  { id: 11, nombre_departamento: "Ica" },
  { id: 12, nombre_departamento: "Junín" },
  { id: 13, nombre_departamento: "La Libertad" },
  { id: 14, nombre_departamento: "Lambayeque" },
  { id: 15, nombre_departamento: "Lima" },
  { id: 16, nombre_departamento: "Loreto" },
  { id: 17, nombre_departamento: "Madre de Dios" },
  { id: 18, nombre_departamento: "Moquegua" },
  { id: 19, nombre_departamento: "Pasco" },
  { id: 20, nombre_departamento: "Piura" },
  { id: 21, nombre_departamento: "Puno" },
  { id: 22, nombre_departamento: "San Martín" },
  { id: 23, nombre_departamento: "Tacna" },
  { id: 24, nombre_departamento: "Tumbes" },
  { id: 25, nombre_departamento: "Ucayali" },
];
