export const jobs = [
  {
    oferta_id: 1,
    empresa: {
      empresa_id: 101,
      empresa_informacion_id: 1,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 1,
      nombre: "A tiempo completo",
    },
    modalidad_trabajo_id: {
      id: 2,
      nombre: "Remoto",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Full Stack",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador full stack con experiencia en React y Node.js para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 2,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 2,
      nombre: "A tiempo parcial",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 3,
    empresa: {
      empresa_id: 103,
      empresa_informacion_id: 3,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 3,
      nombre: "Por horas",
    },
    modalidad_trabajo_id: {
      id: 3,
      nombre: "Híbrido",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Backend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador backend con experiencia en Node.js para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 4,
    empresa: {
      empresa_id: 104,
      empresa_informacion_id: 4,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "google12323123@go.edu.pe",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 1,
      nombre: "A tiempo completo",
    },
    modalidad_trabajo_id: {
      id: 2,
      nombre: "Remoto",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Full Stack",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador full stack con experiencia en React y Node.js para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 5,
    empresa: {
      empresa_id: 105,
      empresa_informacion_id: 5,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "sillicon@eu.com",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 1,
      nombre: "A tiempo completo",
    },
    modalidad_trabajo_id: {
      id: 2,
      nombre: "Remoto",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Full Stack",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador full stack con experiencia en React y Node.js para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 6,
    empresa: {
      empresa_id: 106,
      empresa_informacion_id: 6,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "ivonne@trabjao.com",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 1,
      nombre: "A tiempo completo",
    },
    modalidad_trabajo_id: {
      id: 2,
      nombre: "Remoto",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Full Stack",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador full stack con experiencia en React y Node.js para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 7,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 2,
      nombre: "A tiempo parcial",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 8,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 2,
      nombre: "A tiempo parcial",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 9,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 2,
      nombre: "A tiempo parcial",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 10,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 2,
      nombre: "A tiempo parcial",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 11,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "contact@techinnovations.inc",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 2,
      nombre: "A tiempo parcial",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
  {
    oferta_id: 12,
    empresa: {
      empresa_id: 102,
      empresa_informacion_id: 2,
      sector_id: 3,
      rubro: 1,
      nombre_completo: "Tech Innovations Inc.",
      pais: "Perú",
      departamento_id: 2,
      provincia_id: 5,
      direccion: "1234 Silicon Valley",
      email: "deviozti@gmail.com",
      password: "securepassword",
      sitio_web: "https://www.techinnovations.inc",
      email_code: "XYZ123",
      active: true,
      account_confirm: true,
      avatar: "https://www.techinnovations.inc/avatar.jpg",
      created_at: "2024-01-01T00:00:00Z",
    },
    jornada_id: {
      id: 1,
      nombre: "A tiempo completo",
    },
    modalidad_trabajo_id: {
      id: 1,
      nombre: "Presencial",
    },
    area_id: 5,
    genero_id: 3,
    tiempo_experiencia_id: 2,
    nivel_educacion_id: 4,
    nombre_puesto: "Desarrollador Frontend",
    ocultar_empresa: false,
    vacantes: 3,
    fecha_contratacion: "2024-05-01",
    rango_salarial_min: 3000.0,
    rango_salarial_max: 5000.0,
    tipo_moneda_id: 1,
    ocultar_salario: false,
    pais_id: 67,
    departamento_id: 9,
    provincia_id: 15,
    distrito_id: 7,
    descripcion:
      "Buscamos un desarrollador frontend con experiencia en React para unirse a nuestro equipo dinámico.",
    rango_edad_min: "25",
    rango_edad_max: "40",
    tipo_licencia_id: 0,
    publicacion_automatica: true,
    fecha_publicacion_automatica: "2024-02-25",
    fecha_publicacion_vencimiento_automatica: "2024-03-27",
    estado_oferta_id: 1,
    tipo_contrato_id: 2,
  },
];
