export const jobs = [
  {
    id: 1,
    jobTitle: "Desarrollador Frontend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Colombia, Bogotá",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 2,
    jobTitle: "Desarrollador Backend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Peru, Los Olivos",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 3,
    jobTitle: "Desarrollador Fullstack",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Bolivia, La Paz",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 4,
    jobTitle: "Desarrollador Frontend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Chile, Santiago",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 5,
    jobTitle: "Desarrollador Backend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Peru, San Juan de Lurigancho",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 6,
    jobTitle: "Diseñador UX/UI",
    companyLink: "https://www.apple.com",
    companyName: "Apple",
    location: "Estados Unidos, Cupertino",
    workMode: "Presencial",
    workType: "Jornada Completa",
    date: "15/10/2021",
  },
  {
    id: 7,
    jobTitle: "Ingeniero de Machine Learning",
    companyLink: "https://www.microsoft.com",
    companyName: "Microsoft",
    location: "Canadá, Toronto",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "18/10/2021",
  },
  {
    id: 8,
    jobTitle: "Analista de Datos",
    companyLink: "https://www.amazon.com",
    companyName: "Amazon",
    location: "Alemania, Berlín",
    workMode: "Híbrido",
    workType: "Medio Tiempo",
    date: "20/10/2021",
  },
  {
    id: 9,
    jobTitle: "Desarrollador Mobile",
    companyLink: "https://www.facebook.com",
    companyName: "Facebook",
    location: "Reino Unido, Londres",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "22/10/2021",
  },
  {
    id: 10,
    jobTitle: "Ingeniero DevOps",
    companyLink: "https://www.netflix.com",
    companyName: "Netflix",
    location: "Australia, Sídney",
    workMode: "Presencial",
    workType: "Jornada Completa",
    date: "25/10/2021",
  },
  {
    id: 11,
    jobTitle: "Analista de Seguridad Informática",
    companyLink: "https://www.ibm.com",
    companyName: "IBM",
    location: "India, Bangalore",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "28/10/2021",
  },
  {
    id: 12,
    jobTitle: "Ingeniero de Redes",
    companyLink: "https://www.cisco.com",
    companyName: "Cisco",
    location: "Singapur",
    workMode: "Presencial",
    workType: "Jornada Completa",
    date: "30/10/2021",
  },
  {
    id: 13,
    jobTitle: "Analista de Calidad de Software",
    companyLink: "https://www.oracle.com",
    companyName: "Oracle",
    location: "Italia, Roma",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "02/11/2021",
  },
  {
    id: 14,
    jobTitle: "Especialista en Marketing Digital",
    companyLink: "https://www.adobe.com",
    companyName: "Adobe",
    location: "Francia, París",
    workMode: "Híbrido",
    workType: "Medio Tiempo",
    date: "05/11/2021",
  },
  {
    id: 15,
    jobTitle: "Desarrollador de Videojuegos",
    companyLink: "https://www.ubisoft.com",
    companyName: "Ubisoft",
    location: "Japón, Tokio",
    workMode: "Presencial",
    workType: "Jornada Completa",
    date: "08/11/2021",
  },
];
