export const jobs = [
  {
    id: 1,
    jobTitle: "Desarrollador Frontend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Colombia, Bogotá",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 2,
    jobTitle: "Desarrollador Backend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Peru, Los Olivos",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 3,
    jobTitle: "Desarrollador Fullstack",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Bolivia, La Paz",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 4,
    jobTitle: "Desarrollador Frontend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Chile, Santiago",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
  {
    id: 5,
    jobTitle: "Desarrollador Backend",
    companyLink: "https://www.google.com",
    companyName: "Google",
    location: "Peru, San Juan de Lurigancho",
    workMode: "Remoto",
    workType: "Jornada Completa",
    date: "10/10/2021",
  },
];
