export const sectorCompany = [
    { label: "Administración / Oficina", id: 1 },
    { label: "Almacén / Logistica / Transporte", id: 2 },
    { label: "Atención a clientes", id: 3 },
    { label: "Auditoria", id: 4 },
    { label: "Banca / Servicios Financieros", id: 5 },
    { label: "Banca de Empresas", id: 6 },
    { label: "Banca de Personas", id: 7 },
    { label: "Banca Privada", id: 8 },
    { label: "Belleza y Estética", id: 9 },
    { label: "Bodega", id: 10 },
    { label: "CallCenter / Telemercado", id: 11 },
    { label: "Comunicación y Periodismo", id: 12 },
    { label: "Compras / Comercio Exterior", id: 13 },
    { label: "Construcción y obra", id: 14 },
    { label: "Contabilidad / Finanzas", id: 15 },
    { label: "Dirección / Gerencia", id: 16 },
    { label: "Diseño / Artes gráficas", id: 17 },
    { label: "Educación / Docencia e Investigación", id: 18 },
    { label: "Farmacia", id: 19 },
    { label: "Hostelería / Turismo", id: 20 },
    { label: "Informática / Telecomunicaciones / Tecnologia", id: 21 },
    { label: "Ingeniería / Calidad", id: 22 },
    { label: "Investigación y Calidad", id: 23 },
    { label: "Legal / Asesoría", id: 24 },
    { label: "Mantenimiento y Reparaciones Técnicas", id: 25 },
    { label: "Medicina / Salud", id: 26 },
    { label: "Mercadotecnía / Publicidad / Comunicación", id: 27 },
    { label: "Producción / Operarios / Manufactura", id: 28 },
    { label: "Pesca", id: 29 },
    { label: "Recursos Humanos", id: 30 },
    { label: "Servicios Generales / Aseo y Seguridad", id: 31 },
    { label: "Seguridad Ocupacional y Medio Ambiente", id: 32 },
    { label: "Ventas", id: 33 },
    { label: "Otros", id: 34 }
  ];
  